"""add security answers

Revision ID: 70aa02ae9484
Revises: 
Create Date: 2025-07-28 22:37:57.825882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aa02ae9484'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_answer1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_answer2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_answer3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer3')
    op.drop_column('users', 'security_answer2')
    op.drop_column('users', 'security_answer1')
    # ### end Alembic commands ###
